apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testgo0319-gitops
  description: This is GitOps manifest for testgo0319   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testgo0319
    janus-idp.io/tekton: testgo0319 
    backstage.io/kubernetes-id: testgo0319 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testgo0319
