apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo0319
  janus-idp.io/tekton: testgo0319
  backstage.io/kubernetes-id: testgo0319
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo0319
resources: 
- deployment.yaml
- route.yaml
- service.yaml
